theme:
  name: material
  palette:
    primary: black
  - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
  - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
site_name: Hello2
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
