theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      icon:
        repo: fontawesome/brands/git-alt
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: black
      scheme: slate
      icon:
        repo: fontawesome/brands/git-alt
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
        



repo_url: https://github.com/SupaschaiPh/none1
repo_name: SupaschaiPh/none1
site_name: Hello
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
